### ISSUE TITLE
Camera.concurrentlyTurnTo causing exception

### ISSUE THREAD

**Issue by Gengsta** [RuneMate/Issues#18]
**Describe the bug**
title

**Affected game modes:**
OSRS 

**RuneMate version:**
2.95.11.1

**To Reproduce**
1. run code
2. wait for camera to rotate
3. look at stacktrace
4. contemplate sudoku

```
if (masterFarmer != null && masterFarmer.isVisible()) {
                bot.setStatus("Picking farmer pockets");
                if (masterFarmer.interact("Pickpocket")) {
                    Execution.delayUntil(Local::isMoving, 300);
                } else {
                    masterFarmer.click();
                }
            } else {
                if (masterFarmer != null && Distance.to(masterFarmer) < 7) {
                    bot.setStatus("Rotating camera to farmer");
                    Camera.concurrentlyTurnTo(masterFarmer);
```
```
java.util.FormatFlagsConversionMismatchException: Conversion = o, Flags =  
	at java.util.Formatter$FormatSpecifier.failMismatch(Formatter.java:4298)
	at java.util.Formatter$FormatSpecifier.checkBadFlags(Formatter.java:2997)
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:3107)
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:3083)
	at java.util.Formatter$FormatSpecifier.printInteger(Formatter.java:2787)
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2747)
	at java.util.Formatter.format(Formatter.java:2520)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2981)
	at nul.IiIiIIiiIIIII.final(ThreadFactoryBuilder.java:182)
	at nul.IiIiIIiiIIIII.try(ThreadFactoryBuilder.java:70)
	at com.runemate.game.api.hybrid.local.Camera.try(Camera.java:272)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at com.runemate.game.api.hybrid.local.Camera.concurrentlyTurnTo(Camera.java:272)
	at com.runemate.game.api.hybrid.local.Camera.concurrentlyTurnTo(Camera.java:150)
	at com.runemate.game.api.hybrid.local.Camera.concurrentlyTurnTo(Camera.java:326)
	at com.gengsta.bots.masterfarmer.tasks.Thiever.execute(Thiever.java:59)
	at com.runemate.game.api.script.framework.task.TaskBot.onLoop(TaskBot.java:25)
	at com.runemate.game.api.script.framework.LoopingBot.run(LoopingBot.java:59)
	at com.runemate.game.api.script.framework.AbstractBot.start(AbstractBot.java:301)
	at nul.iIIiiIiiIIIII.run(BotThread.java:28)
```

at com.gengsta.bots.masterfarmer.tasks.Thiever.execute(Thiever.java:59) = Camera.concurrentlyTurnTo(masterFarmer);

**Expected behaviour**
Camera to rotate concurrently

**Screenshots**
https://gmagic.is-terrible.com/ngGcC.png - my account crying in exception after crash (red flag on map never goes away btw)

**Additional context**
pls resolve

**Comment by Gengsta** [comment]
Related to bots name, resolved in next update (tm)
