### ISSUE TITLE
High resolutions cause RM client to run out of memory when loading many pages

### ISSUE THREAD

**Issue by ghost** [RuneMate/Issues#36]
**Describe the bug**
When you run the Runemate client at high resolution, and navigate through multiple pages, and have a bot running, the RM client will inevitably run out of memory and freeze/crash/distort. JFX uses more memory for displaying stuff + caching larger data, and you have the bot UI on top of it.

Cloud:
"run out of memory on high res displays such as when enlarged or maximized. doesn't always crash or freeze immediately but distorts.
    3440x1440 (UHD?)
    3840x2160 (4k, w/HDR)"

**Affected game modes:**
OSRS confirmed.
RS3 very likely due to nature of bug.

**RuneMate version:**
2.95.17, and many previous versions.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run RM on high resolution monitor
2. Load multiple pages (account, bot overview, add instance, etc) + a bot with UI
3. Wait

*Please include the code used to produce this bug.*
Any bot with UI.

**Expected behaviour**
No freezing/crashing/distorting.

**Screenshots**
N/A

**Additional context**
    3440x1440 (UHD?)
    3840x2160 (4k, w/HDR)
- RuneMate has ran out of accessible memory, try allocating more next time you run it.
- java.lang.OutOfMemoryError
    at sun.misc.Unsafe.allocateMemory(Native Method)
    at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:127)
    at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
    at com.sun.prism.impl.BufferUtil.newByteBuffer(BufferUtil.java:90)
    at com.sun.prism.impl.BufferUtil.newIntBuffer(BufferUtil.java:121)
    at com.sun.prism.impl.QueuedPixelSource.getUnusedPixels(QueuedPixelSource.java:153)
    at com.sun.javafx.tk.quantum.UploadingPainter.run(UploadingPainter.java:147)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
    at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
    at java.lang.Thread.run(Thread.java:748)

**Comment by Snufalufugus** [comment]
I use -sdk -login=usn:pw -Xmx1300M as run config

**Comment by ccarpenter04** [comment]
As a result of JavaFX making heavy use of off-heap memory and 32bit processes generally being limited to accessing 2GB of RAM on Windows, allocating less memory for the heap actually makes this issue occur less at the obvious expenses.
